server:
  port: 8082

spring:
  application:
    name: testhub-project

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        enabled: false
      config:
        server-addr: localhost:8848
        file-extension: yml
        enabled: false

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testhub;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 5

  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      encoding: utf-8

  redis:
    host: localhost
    port: 6379
    database: 0
    # ===== 开发环境禁用 Redis =====
    enabled: false

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.testhub.project.entity
  global-config:
    db-config:
      id-type: ASSIGN_ID
